pages/urls.py
from django.urls import path, include

from .views import *

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('about/', AboutPageView.as_view(), name='about'),
    path('instructors/', InstructorPageView.as_view(), name='instructors'),
    path('terms-and-conditions/', TermsPageView.as_view(), name='terms'),
    path('general/info/', RegistrationDetails.as_view(), name='registration_info'),
    path('update/', TemporaryNotificationView.as_view(), name='update'),
    path('contact/', ContactPageView.as_view(), name='contact'),
    path('contact/success/', SuccessContactPageView.as_view(), name='success_contact'),
]

pythoncamp_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler403

handler403 = 'pages.views.error403_view'
handler404 = 'pages.views.error404_view'

urlpatterns = [
    path('definitely-not-admin/', admin.site.urls),

    path('paypal/', include('paypal.standard.ipn.urls')),
    path('accounts/', include('users.urls')),
    path('accounts/', include('allauth.urls')),
    path('tinymce/', include('tinymce.urls')),
    
    
    
    

    path('courses/', include('classes.urls')),


    path('', include('pages.urls')),

]

posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.conf import settings
from django.urls import reverse
from datetime import datetime, timedelta
from classes.models import Class

from django.utils import timezone
from tinymce.models import HTMLField

    
def x_ago_helper(diff):
    if diff.days // 365 >= 2:
        return f'{diff.days // 365} years ago'
    if diff.days // 365 == 1:
        return f'1 year ago'
    if diff.days // 30 >= 2:
        return f'{diff.days // 30} months ago'
    if diff.days // 30 == 1:
        return f'1 month ago'
    if diff.days > 1:
        return f'{diff.days} days ago'
    if diff.days == 1:
        return f'{diff.days} day ago'
    if diff.seconds < 60:
        return f'{diff.seconds} seconds ago'
    if diff.seconds // 60 == 1:
        return '1 minute ago'
    if diff.seconds < 3600:
        return f'{diff.seconds // 60} minutes ago'
    return f'{diff.seconds // 3600} hours ago'


class Post(models.Model):
    title = models.CharField(max_length=1000)
    body = HTMLField(default='')
    date = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    valid = models.BooleanField(default=True)

    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )
    
    
    course = models.ForeignKey(
        Class,
        on_delete=models.CASCADE,
    )
        
    def x_ago(self):
        diff = timezone.now() - self.date
        return x_ago_helper(diff)
    def x_ago_updated(self):
        diff = timezone.now() - self.date_updated
        return x_ago_helper(diff)


    # def save(self, *args, **kwargs):
        
    #     self.date_updated = datetime.now()

    #     super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    
    def edited(self):
        time_difference = self.date_updated - self.date
        if abs(time_difference.total_seconds()) > 30:
            return True
        return False

    def get_name(self):
        return f'{self.author.first_name} {self.author.last_name}'

    # def get_absolute_url(self):
    #     return reverse('post_detail', args=[str(self.id)])
    

class Comment(models.Model):
    body = models.TextField()

    user = models.ForeignKey(
        get_user_model(), 
        on_delete=models.CASCADE,
    )
    post = models.ForeignKey(
        Post, 
        on_delete=models.CASCADE,
    )
    valid = models.BooleanField(default=True)

    date = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def x_ago(self):
        diff = timezone.now() - self.date
        return x_ago_helper(diff)
    def x_ago_updated(self):
        diff = timezone.now() - self.date_updated
        return x_ago_helper(diff)

    def edited(self):
        time_difference = self.date_updated - self.date
        if abs(time_difference.total_seconds()) > 30:
            return True
        return False

    class Meta:
        ordering = ['date']

    def __str__(self):
        return f'Comment by { self.user.first_name } { self.user.last_name } on { self.post.title }'

    def get_name(self):
        return f'{self.author.first_name} {self.author.last_name}'

posts/views.py
from django.shortcuts import render

# Create your views here.

templates/posts/comment_new.html
{% extends '_base.html' %}
{% load icon %}
{% load crispy_forms_tags %}

{% block title %}New Comment{% endblock title %}


{% block content %}
    <h1>New Comment</h1>
    <p>Posting comment under the user with email {{ request.user.email }}.</p>
    <p>A new commenting system will be added so that you don't have to come to 
    a new page to enter a comment. The implementation is challenging (uses AJAX, if you're interested) and has not been figured out yet. Stay tuned!</p>
    
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success" type="submit">Post</button>
    </form>
    
{% endblock content %}

templates/posts/post_delete.html
<!-- templates/post_delete.html -->


{% extends '_base.html' %}
{% load icon %}

{% block title %}Delete Post{% endblock title %}

{% block content %}
    <h1>Delete '{{ object.title }}'</h1>
    <p><a class="text-muted" href="{% url 'forum_list' object.course.slug %}">{% icon 'arrow-left' height="18" width="18" %} {{ object.course.name }} forum</a></p>
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object.title }}"?</p>
        <button class="btn btn-danger" type="submit">Confirm</button>
    </form>
{% endblock content %}

templates/posts/post_detail.html
{% extends '_base.html' %}

{% load icon %}

{% block title%}{{ object.title }} | {{ object.course.name }}{% endblock title %}

{% block content %}

<h1>{{ object.title }}</h1>
<p><a class="text-muted" href="{% url 'forum_list' object.course.slug %}">{% icon 'arrow-left' height="18" width="18" %} {{ object.course.name }} forum</a></p>

{% if request.user == object.author %}
<span class="text-info">by {{ object.author.first_name }} {{ object.author.last_name }}
    {% if object.author.is_staff %}
        {% icon 'headphones' height="16" width="16" %}
    {% endif %}
{% else %}
<span class="text-muted">by {{ object.author.first_name }} {{ object.author.last_name }}
    {% if object.author.is_staff %}
        {% icon 'headphones' height="16" width="16" %}
    {% endif %}
{% endif %}

</span><br>
<span class="text-muted"><small>{{ object.x_ago }}

    {% if object.edited %} 
     (edited)
    {% endif %}</small></span>

{% if post.author == request.user or request.user.is_staff %}
<div style="float:right;">
    <a class= "btn btn-danger btn-sm" href="{% url 'forum_delete' object.course.slug object.id %}">{% icon 'trash-2' height="18" width="16" %} Delete</a>
    <!-- <div class="divider"></div> -->
    <a class="btn btn-outline-secondary btn-sm" href="{% url 'forum_edit' object.course.slug object.id %}">{% icon 'edit' height="18" width="16" %} Edit</a>  
</div>

{% endif %}


<br><br>


{{ object.body|safe }}



<br><br>

<h4>Comments ({{ object.comment_set.all.count }})</h4>
<br>
<hr class="my-0">
{% for comment in object.comment_set.all %}
<div class="card rounded-1 border-0">
    <div class="card-body">

    <p class="card-text"><span class="comment">{{ comment.body|safe|urlize }}</span></p>
    <p class="card-text text-muted">
        <small>comment by 
        {% if comment.user == request.user %}<span class="text-info">
                {{ comment.user.first_name }} {{ comment.user.last_name }} 
                {% if comment.user.is_staff %}
                    {% icon 'headphones' height="13" width="13" %}
                {% endif %}
            </span>
            {% else %}
            {{ comment.user.first_name }} {{ comment.user.last_name }} 
                {% if comment.user.is_staff %}
                    {% icon 'headphones' height="13" width="13" %}
                {% endif %}
        
        {% endif %}
            
            
            
            &middot; {{ comment.x_ago }} 
            {% if comment.edited %} (edited) {% endif %}</small>
    </p>
    <hr style="width:100%" class="mb-0">
    </div>
    
</div>

{% endfor %}



 <form method="POST" id="post-form">
    {% csrf_token %}
    
     <div class="form-group">
       <textarea class="form-control rounded-1" style="padding: 20px;" autocomplete="off" rows="3" id="body" placeholder="Enter Comment Here." ></textarea>
     </div>
     <button type="submit" class="btn btn-primary" id="submit-form">Submit</button>
  </form> 
  
  {% endblock content %}

   {% block javascript %}
   
<script>

    
$(function() { 
    var count = 0;
    $('#post-form').on('submit', function(e){
        e.preventDefault();
        var body = $('#body').val();
        if (body.trim() == "" && count === 0) {
            count++;
            $('#body').addClass('is-invalid')
            $('.form-group').append(
                '<div class="invalid-feedback">'+
                'Please enter in a comment' +
                '</div>'
            )

        }
        else if(body.trim() !== "") {
        $.ajax({
            
            type:'POST',
            url:'{% url "comment_new" object.course.slug object.id %}',
            
            data:{
                body:$('#body').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success:function(json){
                
                console.log(json.title)

                console.log('Beegle beegle bee')
                location.reload()
                // $(".posts").prepend('<div class="col-md-6">'+
                //     '<div class="card-body">' +
                //         '<p class="card-text"><span class="comment">{{ comment.body|safe|urlize }}</span></p>' +
                //             '<h3 class="mb-0">' + json.title + '</h3>' +
                //             '<p class="mb-auto">' + json.description + '</p>' +
                //         '</div>' +
                //     '</div>' +
                // '</div>' 
                // )
            },
            error : function(xhr,errmsg,err) {
            console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
        }
        });
        }
});
})
</script> 

{% endblock javascript %}

templates/posts/post_edit.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}
{% load icon %}

{% block title%}Edit {{ object.title }}{% endblock title %}

{% block content %}

{% block others %}

{{ form.media }}

{% endblock others %}

<h1>
    Edit '{{ object.title }}'
</h1>

<p><a class="text-muted" href="{% url 'forum_list' object.course.slug %}">{% icon 'arrow-left' height="18" width="18" %} {{ object.course.name }} forum</a></p>

<!-- <br> -->

<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-info" type="submit">Update</button>
</form>

<br>

{% endblock content %}

templates/posts/post_list.html
{% extends '_base.html' %}

{% load icon %}

{% block title%}{{ object.name }} Forum{% endblock title %}

{% block content %}

<h1>{{ object.name }} Forum <span class="icon"> <i class="devicon-{{ object.get_icon_string }}-plain"></i></span></h1>

<p><a class="text-muted" href="{% url 'lesson_list' object.slug %}">{% icon 'arrow-left' height="18" width="18" %} {{ object.name }}</a></p>
<a class="btn btn-outline-secondary" href="{% url 'forum_new' object.slug %}" style="float: right;">+ Post</a>
<br>
<!-- <p class="lead">Go to <a href="{% url 'lesson_list' object.slug %}">course</a>.</p> -->



<!-- <br> -->
<p>Posts ({{ object.post_set.all.count }})</p>
{% if object.post_set.all %}
{% for post in object.post_set.all %}
<div class="card">
    <div class="card-body">

    <p class="card-text">
        <a href="{% url 'forum_detail' object.slug post.pk %}" class="font-weight-bold text-dark">{{ post.title }}</a>
        
    </p>
    <p class="card-text text-muted">
        <small>posted by {% if post.author == request.user %}<span class="text-info">
            {{ post.author.first_name }} {{ post.author.last_name }} {% if post.author.is_staff %}{% icon 'truck' height="13" width="13" %}{% endif %}
            </span>
            {% else %}
            {{ post.author.first_name }} {{ post.author.last_name }} {% if post.author.is_staff %}{% icon 'truck' height="13" width="13" %}{% endif %}
            {% endif %}
            &middot; {{ post.x_ago }} 
        {% if post.edited %} (edited) {% endif %}
        {% if post.author == request.user or request.user.is_staff %}
        <span style="float:right;"><a href="{% url 'forum_edit' object.slug post.id %}">Edit</a> | <a href="{% url 'forum_delete' object.slug post.id %}">Delete</a></span>   
        {% endif %}
        </small>
    </p>
    
    </div>
</div>

<br />
    

{% endfor %}
{% else %}
<p class="lead">No Posts Yet! Be the first one!</p>
{% endif %}

{% endblock content %}

templates/posts/post_new.html
<!-- templates/post_new.html -->

{% extends '_base.html' %}
{% load icon %}
{% load crispy_forms_tags %}

{% block title %}New Post{% endblock title %}


{% block others %}

{{ form.media }}

{% endblock others %}

{% block content %}
    <h1>New Post</h1>
    
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success" type="submit">Post</button>
    </form>
    
{% endblock content %}