pages/urls.py
from django.urls import path, include

from .views import *

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('about/', AboutPageView.as_view(), name='about'),
    path('instructors/', InstructorPageView.as_view(), name='instructors'),
    path('terms-and-conditions/', TermsPageView.as_view(), name='terms'),
    path('general/info/', RegistrationDetails.as_view(), name='registration_info'),
    path('update/', TemporaryNotificationView.as_view(), name='update'),
    path('contact/', ContactPageView.as_view(), name='contact'),
    path('contact/success/', SuccessContactPageView.as_view(), name='success_contact'),
]

pythoncamp_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler403

handler403 = 'pages.views.error403_view'
handler404 = 'pages.views.error404_view'

urlpatterns = [
    path('definitely-not-admin/', admin.site.urls),

    path('paypal/', include('paypal.standard.ipn.urls')),
    path('accounts/', include('users.urls')),
    path('accounts/', include('allauth.urls')),
    path('tinymce/', include('tinymce.urls')),
    
    
    
    

    path('courses/', include('classes.urls')),


    path('', include('pages.urls')),

]

users/urls.py
from django.urls import path

from .views import ProfilePageView, StaffUserListView, PasswordChangeSuccessfulView, MyCustomPasswordChangeView

urlpatterns = [
    # path('signup/', SignupPageView.as_view(), name='signup'),
    path('profile/', ProfilePageView.as_view(), name='profile'),
    path('user-list/', StaffUserListView.as_view(), name='student_list'),
    path('password/change/', MyCustomPasswordChangeView.as_view(), name='account_change_password'),
    path('password/change/success', PasswordChangeSuccessfulView.as_view(), name='password_success'), 
]

lessons/models.py
from django.db import models

from django.urls import reverse
from tinymce.models import HTMLField

from classes.models import Class

class Lesson(models.Model):
    name = models.CharField(max_length=255, null=True)
    number = models.PositiveIntegerField(default=0)

    active = models.BooleanField(default=False)
    summary = HTMLField(null=True, blank=True)

    
    date = models.DateTimeField()

    course = models.ForeignKey(Class, on_delete=models.CASCADE, null=True, default='')
    
    homework = HTMLField(null=True, blank=True)

    embedded_url = models.URLField(blank=True, null=True)
    
    def __str__(self):
        if self.name:
            return self.name
        return "potato"



 

lessons/views.py
from django.shortcuts import render

# Create your views here.

templates/lessons/autopopulate.html
{% extends '_base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title%}Hi Maxwell! Autopopulate form{% endblock title %}

{% block content %}

<h1>Autopopulate Form</h1>
<p class="lead">This will automatically generate a number of lessons so you don't have to do it manually. Only you and I can see this page.
    It will redirect you to the list, and it autopopulates a bunch of stuff for the lessons related to each class. Up to 50 lessons, but that
    is much more than you actually need. Use it modestly :). 
</p>

<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-primary" type="submit">Autopopulate!</button>
</form>

{% endblock content %}

templates/lessons/intro.html
{% extends '_base.html' %}
{% load icon %}

{% block title %}Class Info{% endblock title %}


{% block content %}
<h1>{{ object.introduction.title }}</h1>
{% if request.user.is_staff %}

    <span style="float:right"><a class="text-secondary" href="{% url 'intro_edit' class.slug %}">{% icon 'edit' height="20" width="20" %}</a></span>


{% endif %}

<p><a class="text-muted" href="{% url 'lesson_list' object.slug %}">{% icon 'arrow-left' height="18" width="18" %} {{ object.name }} Forum</a></p>
<br>
{{ object.introduction.body|safe}}

{% endblock content %}

templates/lessons/intro_edit.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}
{% load icon %}

{% block title%}Edit Welcome Message{% endblock title %}

{% block others %}

{{ form.media }}

{% endblock others %}

{% block content %}

<h1>
    Edit '{{ object.course.name }}' Welcome Message
</h1>
<p><a class="text-muted" href="{% url 'lesson_list' object.course.slug %}">{% icon 'arrow-left' height="18" width="18" %} {{ object.course.name }} Forum</a></p>

<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-info" type="submit">Update</button>
</form>

{% endblock content %}

templates/lessons/lesson_create.html
{% extends '_base.html' %}
{% load icon %}
{% load crispy_forms_tags %}


{% block title %}Create Lesson{% endblock title %}

{% block others %}{{ form.media }}{% endblock others %}


{% block content %}

<h1><strong>Create Lesson</strong></h1>
<form action="" method="post">{% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-success ml- " type="submit">Save</button>
</form>
{% endblock content %}

templates/lessons/lesson_detail.html
{% extends '_base.html' %}
{% load icon %}
{% load static %}

{% block title %}Lesson {{object.number}}{% endblock title %}



{% block content %}
<h1>Lesson {{ object.number }}: {{ object.name }}

    {% if user.is_staff %}
    <span style="float:right"><a class="text-secondary" href="{% url 'lesson_edit' object.course.slug object.id %}">{% icon 'edit' height="20" width="20" %}</a></span>
{% endif %}
</h1>

<p><a class="text-muted" href="{% url 'lesson_list' object.course.slug %}">{% icon 'arrow-left' height="18" width="18" %} {{ object.course.name }}</a></p>
<br>
Lesson Date: {{ object.date|date:"SHORT_DATE_FORMAT" }}
{% if object.active %}
<br><br>
    
    
    {{ object.summary|safe }}
    {% if object.embedded_url %}
    <br>
    <div class="video" style="text-align: center;">
        <iframe src="{{ object.embedded_url }}" style="max-width: 100%; width: 560px; height: 315px;" allowfullscreen></iframe>
    </div>
    {% endif %}
    <br>
    
    
    <h2>Homework</h2>
    {{ object.homework|safe }}

    


{% else %}
    {% if request.user.is_staff %}
    <br>
    <p>This lesson is not active yet. The students cannot see it until you make it active (after class has past).</p>
    <br>
    
    {{ object.summary|safe }}
    
    
    
    
    
    <br>
    
    
    <h2>Homework</h2>
    {{ object.homework|safe }}
    {% else %}

    <p>The notes for this class will be available on {{ object.date|date:"SHORT_DATE_FORMAT" }}</p>
    <p>Go back to <a href="{% url 'lesson_list' object.course.slug %}">lesson list</a>.</p>
    {% endif %}
{% endif %}


	

{% endblock content %}

templates/lessons/lesson_edit.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}
{% load icon %}
{% load static %}

{% block title%}Edit Lesson {{ object.number }}{% endblock title %}
{% block others %}

{{ form.media }}

{% endblock others %}

{% block content %}


<h1>
    {{ object.name }}
</h1>

<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-info" type="submit">Update</button>
</form>


{% endblock content %}

templates/lessons/lesson_overview.html
{% extends '_base.html' %}

{% load icon %}

{% block title%}{{ object.name }}{% endblock title %}

{% block content %}

<h1>{{ object.name }} <span class="icon"> <i class="devicon-{{ object.get_icon_string }}-plain"></i></span>
</h1>
<a class="text-muted" href="{% url 'registered_classes' %}">{% icon 'arrow-left' height="18" width="18" %} Class List</a>

<!-- {% comment %}
{% if request.user.is_staff %}
    <a href="{% url 'auto_populate' object.slug %}">Generate Lessons +</a>    
       
{% endif %}{% endcomment %} -->

<a style="float:right" href="{% url 'forum_list' object.slug %}" class="btn btn-secondary">Forum {% icon 'list' height="18" width="18" %}</a>

<br>
<br>
<p class="lead">All the lessons we do will show up here! Click on the welcome link to get started. The lessons will be updated after we complete each one. 
    Feel free to ask any questions in the forum!</p>

 {% if user.is_staff %}
    <span style="float:right"><a class="text-secondary" href="{% url 'lesson_create' class.slug %}">{% icon 'file-plus' height="20" width="20" %}</a></span><br>
{% endif %}
   
<p class="lead"><a href="{% url 'lesson_intro' object.slug %}">{{ object.introduction }}</a></p>

{% if object.lesson_set.all %}

{% for lesson in object.lesson_set_order_by_date %}
{% if request.user.is_staff %}
<p class="lead"><a href="{% url 'lesson_detail' object.slug lesson.id %}">Lesson {{ lesson.number}}: {{ lesson.name }}</a> 
    
        {% if lesson.active %}
            {% icon 'check-circle' style="color:green" height="15" width="15" %}
        {% else %}
            {% icon 'x' style="color:red" height="15" width="15" %}
        {% endif %}
    
</p>


{% else %}
{% if lesson.active %}
<p class="lead"><a href="{% url 'lesson_detail' object.slug lesson.id %}">Lesson {{ lesson.number}}: {{ lesson.name }}</a> 
{% endif %}
{% endif %}

{% endfor %}

{% else %}
<br>
<p class="lead">There are no lessons yet! The first class begins on <span class="text-info">{{ object.date|date:"DATE_FORMAT" }}</span></p>
{% endif %}
<br><br><br>
{% endblock content %}