pages/urls.py
from django.urls import path, include

from .views import *

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('about/', AboutPageView.as_view(), name='about'),
    path('instructors/', InstructorPageView.as_view(), name='instructors'),
    path('terms-and-conditions/', TermsPageView.as_view(), name='terms'),
    path('general/info/', RegistrationDetails.as_view(), name='registration_info'),
    path('update/', TemporaryNotificationView.as_view(), name='update'),
    path('contact/', ContactPageView.as_view(), name='contact'),
    path('contact/success/', SuccessContactPageView.as_view(), name='success_contact'),
]

pythoncamp_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler403

handler403 = 'pages.views.error403_view'
handler404 = 'pages.views.error404_view'

urlpatterns = [
    path('definitely-not-admin/', admin.site.urls),

    path('paypal/', include('paypal.standard.ipn.urls')),
    path('accounts/', include('users.urls')),
    path('accounts/', include('allauth.urls')),
    path('tinymce/', include('tinymce.urls')),
    
    
    
    

    path('courses/', include('classes.urls')),


    path('', include('pages.urls')),

]

classes/models.py
from django.db import models

from users.models import CustomUser

from datetime import datetime
from datetime import time
import lessons
from django.urls import reverse_lazy
from django.utils import timezone
from tinymce.models import HTMLField

diff = (
    ('Beginner', 'Beginner'),
    ('Intermediate', 'Intermediate'),
    ('Advanced', 'Advanced')
)

instr = (
    ('Eric Chen', 'Eric Chen'),
    ('Maxwell Zhang', 'Maxwell Zhang')
)

code_languages = (
    ('Django', 'Django'),
    ('Python', 'Python'),
    ('C++', 'C++'),
    ('Java', 'Java'),
    ('HTML5', 'HTML5'),
)
day_of_week = (
    ('Sunday', 'Sunday'),
    ('Monday', 'Monday'),
    ('Tuesday', 'Tuesday'),
    ('Wednesday', 'Wednesday'),
    ('Thursday', 'Thursday'),
    ('Friday', 'Friday'),
    ('Saturday', 'Saturday'),
)

class Class(models.Model):

    name = models.CharField(max_length=255)

    date = models.DateTimeField()
    end_date = models.DateTimeField()

    start_time = models.TimeField()
    end_time = models.TimeField()

    registration_deadline = models.DateTimeField(null=True, default=datetime.now)

    difficulty = models.CharField(max_length=40, choices=diff, default='Beginner') 

    cost = models.FloatField(null=True)
        
    description = models.TextField(null=True)

    syllabus = HTMLField(null=True)

    confirmed = models.BooleanField(default=False)
    
    instructor = models.CharField(max_length=50, choices=instr, default="Eric Chen")
    
    slug = models.SlugField(null=False, unique=True, default=None)

    users = models.ManyToManyField(CustomUser, blank=True, through='Payment', through_fields=('theclass', 'user')) 

    past_payment_deadline = models.BooleanField(default=False)

    first_day = models.CharField(max_length=50, choices=day_of_week, default='Monday')
    

    second_day = models.CharField(max_length=50, choices=day_of_week, null=True, blank=True)


    

    language = models.CharField(max_length=50, choices=code_languages, default='Python')

    embedded_url = models.URLField(blank=True)

    archived = models.BooleanField(default=False)

    def get_icon_string(self):
        if self.language == 'C++':
            return 'cplusplus'
        return self.language.lower()

    def get_days_week(self):
        return [self.first_day, self.second_day]

    def is_ongoing(self):
        if timezone.now() > self.date and timezone.now() < self.end_date:
            return True
        return False
    def past(self):
        if timezone.now() > self.end_date:
            return True
        return False

    
    def later(self):
        if timezone.now() < self.date:
            return True
        return False

    def payment_deadline_date(self):
        delta = timezone.timedelta(seconds=1)
        diff = self.date - delta

        return diff
    
    def start_date_format(self):
        the_date = self.date - timezone.timedelta(seconds=1)

        return the_date.strftime('%-m/%d/%Y at %-I:%M %p')
    

    def show_users(self):
        return ', '.join([a.email for a in self.users.all()])

    def start_date_string(self):
        return self.date.strftime("%b %-d")

    def end_date_string(self):
        return self.end_date.strftime("%b %-d")

    def cost_decimal(self):
        return round(self.cost)

    def start_time_convert(self):
        return self.start_time.strftime("%-I:%M %p")

    def end_time_convert(self):
        return self.end_time.strftime("%-I:%M %p")

    def registration_deadline_string(self):
        return self.registration_deadline.strftime("%b %-d")
    
    def past_registration_deadline(self):
        try: 
            if timezone.now() > self.registration_deadline:
                return True
            return False
        except:
            return False


    
    def paid_users_list(self):
        """ 
        Returns the users who have paid.
        """
        students = self.users.filter(payment__paid=True)
        return students
    
    def registered_users_list(self):
        """
        Lists the users who have registered but not paid.
        """

        students = self.users.filter(payment__paid=False)

        return students

    
    
    @classmethod
    def auto_populate_courses(cls, class_, num):
        for count in range(1, num+1):
            name = f'Class {count}'
            lesson = lessons.models.Lesson(course=class_, name=name, number=count)
            lesson.save()
    

    def lesson_set_order_by_date(self):
        return self.lesson_set.all().order_by('date')

    class Meta:
        ordering = ('name', )
    
    def __str__(self):
        return f'{self.name} {self.date.month}/{self.date.year}' 

    def get_absolute_url(self):
        return reverse_lazy('class_detail', kwargs={'slug': self.slug})

    def save(self, **kwargs):
        try:
            intro = self.introduction
            super(Class, self).save()  
            
        except:
            super(Class, self).save()
            welcome = f'Welcome to {self.name}!'
            intro = Introduction(title=welcome, course=self)
            super(Class, self).save()  
            intro.save()
          

          


class Payment(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    theclass = models.ForeignKey(Class, on_delete=models.CASCADE)

    paid = models.BooleanField(default=False)

    cost = models.FloatField(default=0)
    
    

    # apply_late_fee = models.BooleanField(default=False)


class Introduction(models.Model):
    title = models.CharField(max_length=500, blank=True)

    body = HTMLField(default='')

    course = models.OneToOneField(
        Class, 
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.title

templates/_base.html
{% load static %}
{% load icon %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Pulsar Academy{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- flavicon -->
  <link rel="shortcut icon" type="image/png" href="{% static '/images/favicon.png' %}" />
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  <link rel="stylesheet" href="{% static 'css/toastr.css'%}">
  <!-- TEMPORARY SOLUTION -->
  <style>
    .dropdown:hover>.dropdown-menu {
    display: block;
}
.dropdown-menu:hover {
    display: block;
}


.dot {
    height: 30px;
    width: 30px;
    border: 2px solid #007bff;
    color: #007bff;
    border-radius: 50%;
    display: inline-block;
    transition: 0.3s;
}

.dot:hover {
    background-color: #007bff;
    color: white;
    
}

.menu {
    margin: -10px;
    height: 31px;
    width: 31px;
    border-radius: 50%;
    display: inline-block;
    transition: 0.3s;
    border: none; 
    background: none;
}
.menu:hover {
    background-color: #dfe2e8;
}

.menu:focus {
    background-color: #dbf2ff;
}

.menu-icon {
    position: relative; 
    right: 5px; 
    bottom: 2px; 
    margin-right: 5px;
    height:18px;
    width: 18px;
}

.navbar-icon {
    position: relative;
    right: 5px;
    bottom: 2px;
    margin-right: 5px;
    height: 25px;
    width: 25px;
}


  </style>
  
  <link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css">
  <link rel="stylesheet" href="{% static 'aos-master/dist/aos.css'%}" />
  <link href="{% static 'css/prism.css' %}" rel="stylesheet" />

  {% block others %}{% endblock others %}
</head>
<body>
  <header>

    <!-- Fixed navbar -->
    {% url 'about' as about %}
    <nav{% if request.path == '/' or request.path ==  about or request.path == '/courses/' %} class="navbar navbar-expand-md navbar-dark bg-dark" {% else %} class="navbar navbar-expand-md navbar-dark bg-dark mb-4" {% endif %}>
      <a href="{% url 'home' %}" class="navbar-brand font-weight-normal">Pulsar Academy</a>
      <ul class="navbar-nav mr-auto">
       
        {% url 'summary' as summary %}
        {% url 'checkout' as checkout %}
        {% url 'instructors' as instructors %}
        {% url 'staff_list' as staff_list %}
        {% url 'contact' as contact %}
        <li {% if 'courses' in request.path and request.path != staff_list and request.path != summary and request.path != checkout %} class="nav-item dropdown active" {% else %} class="nav-item dropdown" {% endif %}>
          
         
          <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false">
            Courses
          </a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'class_list' %}">List</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'registered_classes' %}">My Courses</a>
            {% comment %}
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'paid_classes' %}">Paid Courses</a>{% endcomment %} 
            
            
          </div>
          
          
        </li>

        <li {% if request.path == about %} class="nav-item active" {% else %} class="nav-item" {% endif %}><a class = "nav-link" href="{% url 'about' %}">About</a></li>
        {% comment %}<li {% if request.path == instructors %} class="nav-item active" {% else %} class="nav-item" {% endif %}><a class = "nav-link" href="{% url 'instructors' %}">Instructors</a></li>{% endcomment %}
        <li {% if request.path == contact %} class="nav-item active" {% else %} class="nav-item" {% endif %}><a class = "nav-link" href="{% url 'contact' %}">Support</a></li>
        {% if request.user.is_staff %}
        <li {% if request.path == staff_list %} class="nav-item active" {% else %} class="nav-item" {% endif %}><a class = "nav-link" href="{% url 'staff_list' %}">Staff</a></li>
        {% endif %} 
        <!-- ADD FORUM PAGE -->
      </ul>

      <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                {% if user.is_authenticated %}
                    <ul class="navbar-nav ml-auto">
                    
                      <li class="nav-item"><a {% if request.path == checkout or request.path == summary %} class="nav-link active" {% else %} class="nav-link" {% endif %}
                             href="{% url 'summary' %}">{% icon "shopping-cart" class="css-class" height="20" width="20" %} {{ request.user.num_payments_not_paid }}</a></li>
                    
                        <li class="nav-item dropdown">
                            
                            <a class="nav-link dropdown-toggle" href="#" id="userMenu"
                                data-toggle="dropdown" aria-haspopup="true"
                                aria-expanded="false">
                                {{ user.first_name }} {{ user.last_name }}
                            </a>
                            
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                                <a class="dropdown-item" href="{% url 'account_change_password' %}">Change password</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'profile' %}">{% icon 'user' class="navbar-icon" %} Profile</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'account_logout' %}">{% icon 'log-out' class="navbar-icon" %} Log Out</a>
                            </div>

                            
                            
                        </li>
                    </ul>
                {% else %}
                    <form class="form-inline ml-auto">
                        <a href="{% url 'account_login' %}" class="btn btn-outline-secondary">Log In</a>
                        <a href="{% url 'account_signup' %}" class="btn btn-primary ml-2">Join</a>
                    </form>
                {% endif %}
            </div>
    </nav>
  </header>
  <div class="wrapper">
  {% block home %}
  
  {% endblock home %}
  {% url 'home' as home %}
    <div {% if request.path == home or request.path == about %}class="container mb-0" {% else %} class="container mb-4" {% endif %}>
        {% block content %}
        {% endblock content %}
        
       

    </div>
    




    <div class="push"></div>
    </div>
    <footer id="footer" class="py-1 bg-dark text-white-50">
      <div class="container text-center">
        <small>&copy;2021 Pulsar Academy. All Rights Reserved.</small>
      </div>
    </footer>
  <!-- JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->

  
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="{% static 'aos-master/dist/aos.js' %}"></script>
  <script src="{% static 'js/prism.js' %}"></script>
  <script src="{% static 'js/toastr.js' %}"></script>

  {% if messages %}
        {% for message in messages %}
            <script>
              toastr.{{ message.tags }} ('{{ message|safe }}')
            </script>
          {% endfor %}
  {% endif %}
    
  {% block javascript %}
  {% endblock javascript %}
  <script>
    AOS.init({
      duration: 1200,
    });

    
    

  </script>

  
</body>
</html>

templates/about.html
{% extends '_base.html' %}
{% load static %}

{% block title%}About{% endblock title %}

{% block home %}
<div class="jumbotron jumbotron-fluid text-white mb-0" id="jumbotron-about" style="background-image: linear-gradient(to bottom, rgba(0,0,0,0.7) 0%,rgba(0,0,0,0.7) 100%), url('{% static 'images/coding_background.png' %}')">
    <div class="container" style="width:100%;">
        <h1 class="display-3 text-info"><u>About</u></h1>
        <p class="lead">Pulsar Academy offers online courses in coding and development, taught by its <a href="{% url 'instructors' %}" target="_blank">creators</a>, rising
            seniors at the Montgomery Blair High School STEM Program. PA was created to offer an accessible way to children of all ages to learn how to code. At PA, we firmly believe that all people 
            should have an understanding of coding and technology, as everything in the world today revolves around computers. Our goal is to
            provide the fundamentals for you to excel at programming and broaden your horizons.</p>
            
            <p class="lead">We aim to instill a love and appreciation for coding, as well as create
            a friendly environment for everyone to be able to engage in the learning process. We will cater to your needs, and will take feedback and try to improve our
            craft. By the end of your course(s), we hope to have expanded your knowledge and skillset, so you are prepared to take on even bigger challenges and solve real-world problems!
    
            
            
            
             
        </p>
    </div>
    <br>
        <div class="container" id="instructors">
            <h2 class="display-4 text-info"><u>Meet the Instructors</u></h2>

<p class="lead">Hi! We will be the instructors for the various courses that we offer. We are Montgomery Blair High School students, and we are very passionate about coding.
    Both of us will teach our own respective courses. Don't be scared! We'll get to know one another. If you want any additional credentials, feel free to message us.
</p><br>
<div class="card-deck"  style="overflow-x: hidden;">
    <div class="card" style="border: none; background-color: rgba(245, 245, 245, 0);" id="ericchen">
      <img class="card-img-top" src="{% static 'images/eric.jpg' %}" alt="Card image cap">
      <br>
        <h4 class="card-title"><b>Eric Chen</b></h4>
        <p class="card-text">Eric is a senior at Montgomery Blair High School. He is an avid web developer and coder, having worked on 
            his school's debate team site as well as <a href="{% url 'home' %}">this website</a>! His favorite languages are Python and Java, and 
            he is currently learning to be an Amazon Web Services Solutions Architect. He has tutored competitive math in the past and enjoys working with others. His hobbies include
            competitive debate, basketball, and listening to music. He will be majoring in Computer Science in college. 

        </p>
        
        
      
     
      
    </div>

    <div class="card" style="border: none; background-color: rgba(245, 245, 245, 0);" id="maxwellzhang">
      <img class="card-img-top" src="{% static 'images/maxwell.png' %}" alt="Card image cap">
      <br>
      <h4 class="card-title"><b>Maxwell Zhang</b></h4>
        <p class="card-text">Maxwell is a senior at Montgomery Blair High School. He has experience teaching Python 
          at Kids Connect in the past. In the professional scene, Maxwell has conducted an internship in machine learning 
          at the Mahmood Lab at Harvard Medical School. Maxwell is an avid competitive programmer, as he is in the USA Computing 
          Olympiad Platinum Division and is a Division I participant on Codeforces. Aside from coding, Maxwell’s hobbies include playing
           viola and reading manga.

        </p>
          
  </div>
</div>
        </div>
        <br><br>       
        
        <div class="container">
            <h2 class="display-4 text-info"><u>FAQs</u></h2><br>
        <p class="lead text-info"><strong>How do the courses work?</strong></p>
        <p>Courses will be held online via <a href="https://meet.google.com/" target="_blank">Google Meet</a>, a video calling service offered by Google. Each course lasts for 5 weeks, with two classes per week based on the course.
            Students will have access to lesson summaries and a class forum to look for guidance and will follow along the instructor during each meeting. Lessons will be
            interactive, and you can look at the syllabus in the <a href="{% url 'class_list' %}" target="_blank">course details</a> You can view detailed information there. 
        </p>
        <br>
        <p class="lead text-info"><strong>How do I register?</strong></p>
        <p>You can make a free account by <a href="{% url 'account_signup' %}" target="_blank">signing up</a>. From there, you can go to the <a href="{% url 'class_list' %}">course list</a>
            and sign up for the courses you want. You can sign up for as few or as many as you would like. Payments will be conducted using Paypal, and will be available once the course is confirmed by our staff. Courses will become available for payment 
            after a minimum quota of students are reached, and a notification email will be sent to the people who have signed up. More information on regsitration
            <a href="{% url 'registration_info' %}" target="_blank">here</a>.
        </p>
        <br>
        <p class="lead text-info"><strong>What will I need?</strong></p>
        <p>Make sure that you are running an updated operating system. Typically, you will be fine if you have either MacOS, Windows, or an updated version of Linux.
            We will go over how to download and set up the programming languages needed for each course. Make sure you have a stable WiFi connection and a working
            microphone. Cameras will not be necessary but are recommended. Screen sharing will be optional but is also recommended to get the most out of our lectures. Lastly, make sure you have sufficient storage, as some packages
            that will be downloaded can potentially be large. 
        </p>
        <br>
        <p class="lead text-info"><strong>Is Pulsar Academy right for me?</strong></p>
        <p>Our services are primarily targeted to beginners or programmers with some experience. Be sure to look at the details of each course that we offer,
            and see if it looks like it is the right fit for you (there are pre-requisites as well). If you feel like you are very advanced, PA is likely not the right choice. However, if you aren't sure,
            feel free to <a href="{% url 'contact' %}">contact us</a> and we can discuss the right choices for you. 
        </p>
        <br>
        <!-- <p class="lead text-info">Is my payment secure?</p>
        <p>Payment is handeled by Paypal, and all your payment information only ever goes to <a href="https://www.paypal.com/us/home" target="_blank">PayPal</a>. We do not record any of your payment credentials, but all 
            traffic coming and going to our site is encrypted anyway. The payment will go towards our business account, currently under the email <span class="text-primary">eric@echen.io</span>.
             Should you have any concerns, feel free to <a href="{% url 'contact' %}">contact us</a> and we can figure taylor to your needs.
        </p><br> -->
        <p class="lead text-info"><strong>How do I contact you?</strong></p>
        <p>Our preferred way of communication is by email. All inquiries should go to <a href="mailto:contact@pulsaracademy.com">contact@pulsaracademy.com</a> or just go <a href="{% url 'contact' %}">here</a>. If you would like to discuss by call, feel free to dial 
            <span class="text-primary">(301)-456-9068</span>, but availability is NOT guaranteed. Emails will be responded to within a day. If you do not receive a reply, you should either call the number above or try again.  
        </p>
        <br>
        <p class="lead text-info"><strong>I'm not receiving notifications from you! What should I do?</strong></p>
        <p>Since this website is solely monitored by us, there could be a few issues. First, make sure the email you entered for your accounts are typed in correctly.
            Next, check your spam box; we are a new business, and it is possible that our emails have been marked as spam. If neither of those are the case, 
            please try to <a href="{% url 'contact' %}">contact us</a>. It could very well be a server issue on our side as well! We will be sure to respond quickly.
        </p>
        <br>
        <p class="lead text-info"><strong>How do I join a meeting?</strong></p>
        <p>An email will be sent prior to each meeting containing the relevant information.
             Make sure you receive an email from signing up and from paying for a course. Students will be
            able to report to the meeting by either a url or invitation link. 
        </p>
        <br>
        <p class="lead text-info"><strong>I'm going to be busy on a class meeting day! What do I do?</strong></p>
        <p>No worries! Classes will be recorded and will be available in the course summary or email. Homework will also be posted. 
             Make sure to let us know if you will miss a class! Any questions
            can always be posted on the forum. 
        </p>
        <br>
        <p class="lead text-info"><strong>Can I get a refund after I've paid?</strong></p>
        <p>Refunds must be requested at least a day prior to the start of the first class. You will receive a refund in full if your request is valid. If you decide
            that the course does not suit your needs, we can negotiate a refund individually.
        </p>  
        <br>
        <p class="lead text-info"><strong>Anything else?</strong></p>
        <p>Actually, yes! We are very new to online teaching, so please be patient with us! This website was coded from scratch, and there could be problems that we 
            don't even know of yet! If you encounter any, you can help the PA community by reporting that to us. Any instructional feedback is also greatly appreciated. We will send out a 
            feedback form after the course is over, but feel free to tell us anything during the course as well. We want to make this a great experience for you!
        </p>  
    </div>
    <br><br>
    <div class="container text-break">
        
        <h3 class="display-4 text-info"><u>Acknowledgements</u></h3><br>
        <p class="lead">Thank you to Kevin Higgs for his extensive help with the development of this site! Without him, the creation of this site
            would have been impossible. Check out his work at <a href="https://kmh.zone">kmh.zone</a>. Also, a big thank you to everyone who 
            gave me suggestions about formatting, design, or structure. 
        </p>
    </div>
    
</div>
{% endblock home %}

templates/contact.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}Contact{% endblock title %}


{% block content %}

<h1><strong>Contact Us</strong></h1>
<hr>


<p class="lead">For all inquiries, please fill out the form below.</p>
<br>

<form method="post">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-6">
            <div class="form-row">
                <div class="form-group col-md-6 mb-0">
                    {{ form.first_name|as_crispy_field }}
                </div>
                <div class="form-group col-md-6 mb-0">
                    {{ form.last_name|as_crispy_field }}
                </div>
                
            </div>
            {{ form.email|as_crispy_field }}
                {{ form.message|as_crispy_field }}
        </div>
        
        
        

    </div>
    

    <button class="btn btn-info">Submit</button>
</form>


{% endblock content %}

templates/error403.html
{% extends '_base.html' %}

{% block title %}Error 403{% endblock title %}


{% block content %}

<h1 class="text-center">Error 403</h1>
<!-- <h3 class="text-center">I'm surprised you found this page...Let me know and you get 100 cool points.</h3> -->
<h4 class="text-center">You do not have access to this page.</h4>

{% endblock content %}

templates/profile.html
{% extends '_base.html' %}

{% load icon %}
{% block title %}Profile{% endblock title %}

{% block content %}
<div class="card">
    <div class="card-header">
        {{ request.user.first_name }} {{ request.user.last_name }}'s Profile
        <span style="float:right"><a href="{% url 'account_change_password' %}">{% icon 'edit-3' height="17" width="17" %} Change Password</a></span>
    </div>

    <div class="card-body">
        <!-- <p>Name: {{ request.user.first_name}} {{ request.user.last_name }}</p> -->
        <p>Email: {{ request.user.email }}</p>
        {% if request.user.parent_email %}
        <p>Parent Email: {{ request.user.parent_email }}</p>
        {% endif %}
        <p>School: {{ request.user.school }}</p>
        Grade: {{ request.user.grade }}
 
    </div>
    
    
</div>
<br>



{% if request.user.class_set.all %}

<!-- Classes not paid -->
{% if request.user.classes_not_paid_list %}
<h2><strong>Registered Courses</strong></h2> <br>
{% comment %}
<div style="float:right;">
    <a class= "btn btn-outline-primary btn-sm" href="{% url 'summary' %}">{% icon 'shopping-cart' height="16" width="16" %} Pay</a>

</div>
{% endcomment %}


{% for class in request.user.classes_not_paid_list %}
<div class="card">
    <div class="card-header">
        <span class="font-weight-bold"><a class="text-dark" href="{% url 'class_detail' class.slug %}">{{ class.name }}</a></span> &middot;
        <span class="text-muted">{{ class.start_date_string }} - {{ class.end_date_string }} &middot; {{ class.first_day }}{% if class.second_day %}, {{ class.second_day }}{% endif %} &middot; {{ class.start_time_convert }} - {{ class.end_time_convert }}</span>
        <span style="float:right" class="text-muted">
            {% if class.confirmed and not class.past_registration_deadline %}
            (Confirmed)
            {% comment %}{% icon 'check-circle' style="color:green" height="15" width="15" %}{% endcomment %}
        {% comment %}{% else %}
            {% icon 'x' style="color:red" height="15" width="15" %} {% endcomment %}
        {% endif %}
        </span>
    </div>

    <div class="card-body">
        {{ class.description }}      
             
    </div>
    <div class="card-footer">
        <span class="text-muted">Instructor: {{ class.instructor }}</span>
  
      </div>
</div>
<br>
{% endfor %}
{% endif %}


<hr>
<br>
<!-- Classes that are paid -->
<h2><strong>Paid Course History</strong></h2><br>
{% if request.user.classes_paid_list %}

{% for class in request.user.classes_paid_list reversed %}

<div class="card">
    <div class="card-header">
        <span class="font-weight-bold"><a class="text-dark" href="{% url 'lesson_list' class.slug %}">{{ class.name }}</a></span> &middot;
        <span class="text-muted">{{ class.start_date_string }} - {{ class.end_date_string }} &middot; {{ class.first_day }}{% if class.second_day %}, {{ class.second_day }}{% endif %} &middot; {{ class.start_time_convert }} - {{ class.end_time_convert }}</span>
        <span style="float:right" class="text-muted">
            <a class="btn btn-info" style="padding-top: 2px; padding-bottom: 2px; padding-left: 3px; padding-right: 3px;" href="{% url 'lesson_list' class.slug %}">{% icon 'book_open' style="padding: -5px" %}</a>
            
            
            
        </span>
    </div>

    <div class="card-body">
        {{ class.description }}      
             
    </div>
    <div class="card-footer">
        <span class="text-muted">Instructor: {{ class.instructor }}</span>
        
        <span class="text-muted" style="float:right">
            {% if class.archived %}
            (Completed)
        {% else %}
            (Ongoing)
        {% endif %}
        </span>
      </div>
    
</div>
<br>
{% endfor %}
{% else %}
<p class="lead">Your paid classes will show up here.</p>
{% endif %}

{% else %}
<p>You are not registered and for any classes! Sign up <a href="{% url 'class_list' %}">here</a>.</p> 

{% endif %}
{% endblock content %}